version: "3"
services:
  webstats:
    # replace username/repo:tag with your name and image details
    image: xaratustrah/webstats_docker:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my_cool_net
    environment:
      - DOCKERHOST_USER=${DOCKERHOST_USER}

  nginx:
    image: webstats_docker_nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"

    networks:
      - my_cool_net

networks:
  my_cool_net:
